"""
Django settings for proyecto_community project.

Generated by 'django-admin startproject' using Django 3.2.25.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

# settings.py
import os
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

# ================================================
# 🟢 DETECCIÓN DE ENTORNO
# ================================================
ON_PYTHONANYWHERE = 'PYTHONANYWHERE_DOMAIN' in os.environ

# ================================================
# 🟢 BASE DE DATOS
# ================================================
if ON_PYTHONANYWHERE:
    # PRODUCCIÓN: SQLite en PythonAnywhere (Plan gratuito)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        }
    }
else:
    # DESARROLLO LOCAL: MySQL (XAMPP)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'mi_app_db',
            'USER': 'root',
            'PASSWORD': '',
            'HOST': 'localhost',
            'PORT': '3306',
        }
    }

# ================================================
# 🟢 CONFIGURACIÓN PARA PRODUCCIÓN
# ================================================
if ON_PYTHONANYWHERE:
    DEBUG = False
    ALLOWED_HOSTS = ['tu_usuario.pythonanywhere.com']
else:
    DEBUG = True
    ALLOWED_HOSTS = []
