# Generated by Django 3.2.25 on 2026-04-26 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=12, unique=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('calle_sector', models.CharField(max_length=100)),
                ('enfermedad_cronica', models.TextField(blank=True, null=True)),
                ('discapacidad', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
