# Generated by Django 6.0.5 on 2026-05-15 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habitante',
            options={'verbose_name': 'Habitante', 'verbose_name_plural': 'Habitantes'},
        ),
        migrations.RemoveField(
            model_name='habitante',
            name='enfermedad_cronica',
        ),
        migrations.AddField(
            model_name='habitante',
            name='jefe_familia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='familiares', to='comunidad.habitante'),
        ),
        migrations.AddField(
            model_name='habitante',
            name='parentesco',
            field=models.CharField(choices=[('JEFE', 'Jefe(a) de Familia'), ('ESPOSO', 'Esposo(a)'), ('HIJO', 'Hijo(a)'), ('NIETO', 'Nieto(a)'), ('PADRE', 'Padre/Madre'), ('OTRO', 'Otro Familiar')], default='JEFE', max_length=20),
        ),
    ]
