# Generated by Django 6.0.5 on 2026-05-15 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0002_alter_habitante_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitante',
            name='genero',
            field=models.CharField(choices=[('M', 'M'), ('F', 'F')], default='M', max_length=1),
        ),
        migrations.AddField(
            model_name='habitante',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
