# Generated by Django 6.0.5 on 2026-05-17 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0003_habitante_genero_habitante_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitante',
            name='enfermedad_cronica',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Enfermedad Crónica'),
        ),
        migrations.AlterField(
            model_name='habitante',
            name='apellidos',
            field=models.CharField(max_length=50, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='habitante',
            name='calle_sector',
            field=models.CharField(max_length=100, verbose_name='Calle o Sector'),
        ),
        migrations.AlterField(
            model_name='habitante',
            name='cedula',
            field=models.CharField(max_length=15, unique=True, verbose_name='Cédula'),
        ),
        migrations.AlterField(
            model_name='habitante',
            name='discapacidad',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Discapacidad'),
        ),
        migrations.AlterField(
            model_name='habitante',
            name='fecha_nacimiento',
            field=models.DateField(verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AlterField(
            model_name='habitante',
            name='genero',
            field=models.CharField(max_length=15, verbose_name='Género'),
        ),
        migrations.AlterField(
            model_name='habitante',
            name='jefe_familia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cargas', to='comunidad.habitante', verbose_name='Jefe de Familia'),
        ),
        migrations.AlterField(
            model_name='habitante',
            name='nombres',
            field=models.CharField(max_length=50, verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='habitante',
            name='parentesco',
            field=models.CharField(choices=[('JEFE', 'Jefe de Familia'), ('ESPOSO', 'Esposo(a) / Conyugue'), ('HIJO', 'Hijo(a)'), ('PADRE', 'Padre / Madre'), ('HERMANO', 'Hermano(a)'), ('NIETO', 'Nieto(a)'), ('OTRO', 'Otro Familiar')], default='JEFE', max_length=20, verbose_name='Parentesco con el Jefe'),
        ),
        migrations.AlterField(
            model_name='habitante',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono'),
        ),
        migrations.CreateModel(
            name='Voceria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comite_codigo', models.CharField(choices=[('ALIM', 'Alimentación y CLAP'), ('SEGU', 'Security e Integridad (Gestión de Riesgos)'), ('VIVI', 'Vivienda y Obras Públicas'), ('SERV', 'Servicios Públicos (Agua, Electricidad, Gas)'), ('SALU', 'Salud y Sanidad Integral'), ('PROT', 'Protección Social'), ('ECON', 'Economía Comunal y Emprendimiento'), ('EDUC', 'Educación, Cultura y Formación'), ('DEPO', 'Deporte y Recreación'), ('JUV', 'Juventud y Nuevas Generaciones'), ('AMBI', 'Ambiente, Ecología y Aseo'), ('COMU', 'Medios y Comunicación Alternativa'), ('FINANZAS', 'Unidad Financiera (Tesorería)'), ('CONTRALORIA', 'Contraloría Social (Fiscalización)')], max_length=20, verbose_name='Comité / Unidad')),
                ('tipo_vocero', models.CharField(choices=[('VOCERO', 'Vocero Principal'), ('SUBVOCERO', 'Subvocero / Suplente')], max_length=15, verbose_name='Tipo de Vocería')),
                ('fecha_asignacion', models.DateField(auto_now_add=True)),
                ('habitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargos_comunales', to='comunidad.habitante', verbose_name='Habitante')),
            ],
            options={
                'verbose_name': 'Vocería Comunitaria',
                'verbose_name_plural': 'Vocerías Comunitarias',
                'unique_together': {('comite_codigo', 'tipo_vocero')},
            },
        ),
    ]
