# Generated by Django 6.0.5 on 2026-05-18 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0004_habitante_enfermedad_cronica_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habitante',
            options={},
        ),
        migrations.RemoveField(
            model_name='habitante',
            name='enfermedad_cronica',
        ),
        migrations.AddField(
            model_name='habitante',
            name='nacionalidad',
            field=models.CharField(choices=[('V', 'Venezolano(a)'), ('E', 'Extranjero(a)')], default='V', max_length=1, verbose_name='Nacionalidad'),
        ),
        migrations.AddField(
            model_name='habitante',
            name='punto_referencia',
            field=models.TextField(blank=True, null=True, verbose_name='Punto de Referencia'),
        ),
        migrations.AlterField(
            model_name='habitante',
            name='calle_sector',
            field=models.CharField(choices=[('Calle 1', 'Calle 1'), ('Calle 2', 'Calle 2'), ('Calle 3', 'Calle 3'), ('Calle 4', 'Calle 4')], max_length=20, verbose_name='Calle o Sector'),
        ),
        migrations.AlterField(
            model_name='habitante',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino (M)'), ('F', 'Femenino (F)')], max_length=1, verbose_name='Género'),
        ),
        migrations.AlterField(
            model_name='habitante',
            name='jefe_familia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='miembros', to='comunidad.habitante', verbose_name='Jefe de Familia Vinculado'),
        ),
        migrations.AlterField(
            model_name='voceria',
            name='comite_codigo',
            field=models.CharField(choices=[('EJECUTIVO', 'Unidad Ejecutiva (Coordinación)'), ('FINANZAS', 'Unidad Administrativa y Financiera'), ('CONTRALORIA', 'Unidad de Contraloría Social'), ('VIVIENDA', 'Vivienda, Hábitat y Tierras'), ('SERVICIOS', 'Servicios Públicos (Agua, Luz, Gas)'), ('SALU', 'Salud y Sanidad Integral'), ('PROT', 'Protección Social y Familia'), ('ECON', 'Economía Comunal y Emprendimiento'), ('EDUC', 'Educación, Cultura y Formación'), ('DEPO', 'Deporte y Recreación'), ('JUV', 'Juventud y Nuevas Generaciones'), ('AMBI', 'Ambiente, Ecología y Aseo'), ('COMU', 'Medios y Comunicación Alternativa')], max_length=20, verbose_name='Comité / Unidad'),
        ),
    ]
