# Generated by Django 6.0.5 on 2026-05-19 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0005_alter_habitante_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habitante',
            options={'verbose_name': 'Habitante', 'verbose_name_plural': 'Habitantes'},
        ),
        migrations.AlterModelOptions(
            name='voceria',
            options={'verbose_name': 'Vocería', 'verbose_name_plural': 'Vocerías'},
        ),
        migrations.AlterField(
            model_name='habitante',
            name='apellidos',
            field=models.CharField(max_length=100, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='habitante',
            name='calle_sector',
            field=models.CharField(choices=[('Calle 1', 'Calle 1'), ('Calle 2', 'Calle 2'), ('Calle 3', 'Calle 3'), ('Calle 4', 'Calle 4')], max_length=50, verbose_name='Calle / Sector'),
        ),
        migrations.AlterField(
            model_name='habitante',
            name='cedula',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='Cédula de Identidad'),
        ),
        migrations.AlterField(
            model_name='habitante',
            name='jefe_familia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='familiares', to='comunidad.habitante', verbose_name='Jefe de Familia Relacionado'),
        ),
        migrations.AlterField(
            model_name='habitante',
            name='nombres',
            field=models.CharField(max_length=100, verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='habitante',
            name='parentesco',
            field=models.CharField(choices=[('JEFE', 'Jefe de Familia'), ('ESPOSO', 'Esposo(a) / Conyugue'), ('HIJO', 'Hijo(a)'), ('PADRE', 'Padre / Madre'), ('HERMANO', 'Hermano(a)'), ('NIETO', 'Nieto(a)'), ('OTRO', 'Otro Familiar')], max_length=20, verbose_name='Parentesco con el Jefe de Familia'),
        ),
        migrations.AlterField(
            model_name='habitante',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono de Contacto'),
        ),
        migrations.AlterField(
            model_name='voceria',
            name='fecha_asignacion',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de Asignación'),
        ),
    ]
