# Generated by Django 6.0.5 on 2026-05-20 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0006_alter_habitante_options_alter_voceria_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voceria',
            name='comite_codigo',
            field=models.CharField(choices=[('EJECUTIVO', 'Unidad Ejecutiva (Coordinación)'), ('FINANZAS', 'Unidad Administrativa y Financiera'), ('CONTRALORIA', 'Unidad de Contraloría Social'), ('VIVIENDA', 'Vivienda, Hábitat y Tierras'), ('SERVICIOS', 'Servicios Públicos (Agua, Luz, Gas)'), ('SALU', 'Salud y Sanidad Integral'), ('PROT', 'Protección Social y Familia'), ('ECON', 'Economía Comunal y Emprendimiento'), ('EDUC', 'Educación, Culture y Formación'), ('DEPO', 'Deporte y Recreación'), ('JUV', 'Juventud y Nuevas Generaciones'), ('AMBI', 'Ambiente, Ecología y Aseo'), ('COMU', 'Medios y Comunicación Alternativa')], max_length=20, verbose_name='Comité / Unidad'),
        ),
        migrations.CreateModel(
            name='JefeCalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle_nombre', models.CharField(choices=[('Calle 1', 'Calle 1'), ('Calle 2', 'Calle 2'), ('Calle 3', 'Calle 3'), ('Calle 4', 'Calle 4')], max_length=50, unique=True, verbose_name='Calle a Cargo')),
                ('fecha_asignacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Designación')),
                ('habitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jefaturas_calle', to='comunidad.habitante', verbose_name='Jefe de Calle')),
            ],
            options={
                'verbose_name': 'Jefe de Calle',
                'verbose_name_plural': 'Jefes de Calle',
            },
        ),
    ]
