# Generated by Django 6.0.5 on 2026-05-21 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0007_alter_voceria_comite_codigo_jefecalle'),
    ]

    operations = [
        migrations.CreateModel(
            name='CensoBombona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bombonas_10kg', models.PositiveIntegerField(default=0, verbose_name='Bombonas 10 Kg')),
                ('bombonas_18kg', models.PositiveIntegerField(default=0, verbose_name='Bombonas 18 Kg')),
                ('bombonas_27kg', models.PositiveIntegerField(default=0, verbose_name='Bombonas 27 Kg')),
                ('bombonas_43kg', models.PositiveIntegerField(default=0, verbose_name='Bombonas 43 Kg')),
                ('fecha_registro', models.DateTimeField(auto_now=True)),
                ('jefe_familia', models.OneToOneField(limit_choices_to={'parentesco': 'JEFE'}, on_delete=django.db.models.deletion.CASCADE, related_name='censo_gas', to='comunidad.habitante', verbose_name='Jefe de Familia')),
            ],
        ),
    ]
