# Generated by Django 6.0.5 on 2026-05-25 03:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0008_censobombona'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Comité')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
            ],
            options={
                'verbose_name': 'Comité',
                'verbose_name_plural': 'Comités',
            },
        ),
        migrations.AlterField(
            model_name='jefecalle',
            name='habitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jefaduras_calle', to='comunidad.habitante', verbose_name='Jefe de Calle'),
        ),
        migrations.AlterField(
            model_name='voceria',
            name='comite_codigo',
            field=models.CharField(choices=[('EJECUTIVO', 'Unidad Ejecutiva (Coordinación)'), ('FINANZAS', 'Unidad Administrativa y Financiera'), ('CONTRALORIA', 'Unidad de Contraloría Social'), ('VIVIENDA', 'Vivienda, Hábitat y Tierras'), ('SERVICIOS', 'Servicios Públicos (Agua, Luz, Gas)'), ('SALU', 'Salud y Sanidad Integral'), ('PROT', 'Protección Social y Familia'), ('ECON', 'Economy Comunal y Emprendimiento'), ('EDUC', 'Educación, Culture y Formación'), ('DEPO', 'Deporte y Recreación'), ('JUV', 'Juventud y Nuevas Generaciones'), ('AMBI', 'Ambiente, Ecología y Aseo'), ('COMU', 'Medios y Comunicación Alternativa')], max_length=20, verbose_name='Comité / Unidad'),
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('recursos_usd', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_aprobacion', models.DateField(default=django.utils.timezone.now)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('APROBADO', 'Aprobado'), ('EN_EJECUCION', 'En Ejecución'), ('CULMINADO', 'Culminado')], default='APROBADO', max_length=20)),
                ('ente_financista', models.CharField(blank=True, max_length=150, null=True)),
                ('ejecutor', models.CharField(blank=True, max_length=150, null=True)),
                ('fecha_inicio_real', models.DateField(blank=True, null=True)),
                ('fecha_cierre_real', models.DateField(blank=True, null=True)),
                ('comite', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proyectos', to='comunidad.comite')),
            ],
        ),
        migrations.CreateModel(
            name='NotaSeguimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('observacion', models.TextField()),
                ('usuario_registro', models.CharField(max_length=100)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='comunidad.proyecto')),
            ],
        ),
    ]
