# Generated by Django 6.0.5 on 2026-05-25 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0009_comite_alter_jefecalle_habitante_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='comite',
            field=models.CharField(choices=[('EJECUTIVO', 'Unidad Ejecutiva (Coordinación)'), ('FINANZAS', 'Unidad Administrativa y Financiera'), ('CONTRALORIA', 'Unidad de Contraloría Social'), ('VIVIENDA', 'Vivienda, Hábitat y Tierras'), ('SERVICIOS', 'Servicios Públicos (Agua, Luz, Gas)'), ('SALU', 'Salud y Sanidad Integral'), ('PROT', 'Protección Social y Familia'), ('ECON', 'Economy Comunal y Emprendimiento'), ('EDUC', 'Educación, Culture y Formación'), ('DEPO', 'Deporte y Recreación'), ('JUV', 'Juventud y Nuevas Generaciones'), ('AMBI', 'Ambiente, Ecología y Aseo'), ('COMU', 'Medios y Comunicación Alternativa')], max_length=50, verbose_name='Comité / Categoría'),
        ),
    ]
