# Generated by Django 6.0.5 on 2026-05-26 16:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0010_alter_proyecto_comite'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoFinanciero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('INGRESO', 'Ingreso (+)'), ('EGRESO', 'Egreso (-)')], max_length=10, verbose_name='Tipo de Movimiento')),
                ('concepto', models.CharField(max_length=255, verbose_name='Concepto / Descripción')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto (USD)')),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Registro')),
                ('usuario_registrador', models.CharField(max_length=150, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Movimiento Financiero',
                'verbose_name_plural': 'Movimientos Financieros',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
