# Generated by Django 6.0.5 on 2026-05-26 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0011_movimientofinanciero'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimientofinanciero',
            options={'verbose_name': 'Movimiento Financiero', 'verbose_name_plural': 'Movimientos Financieros'},
        ),
        migrations.AddField(
            model_name='movimientofinanciero',
            name='moneda',
            field=models.CharField(choices=[('USD', 'Dólares (USD)'), ('BS', 'Bolívares (BS)'), ('COP', 'Pesos Colombianos (COP)')], default='USD', max_length=3, verbose_name='Moneda'),
        ),
        migrations.AlterField(
            model_name='movimientofinanciero',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Monto'),
        ),
    ]
