# Generated by Django 6.0.5 on 2026-06-02 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0012_alter_movimientofinanciero_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='es_compromiso',
            field=models.BooleanField(default=True),
        ),
    ]
