# Generated by Django 6.0.5 on 2026-06-05 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0013_proyecto_es_compromiso'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitante',
            name='fecha_ingreso',
            field=models.DateField(default='2026-06-05', verbose_name='Radicado desde'),
            preserve_default=False,
        ),
    ]
