# Generated by Django 6.0.5 on 2026-06-08 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0014_habitante_fecha_ingreso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitante',
            name='calle_sector',
            field=models.CharField(choices=[('Monjas I', 'Monjas I'), ('Monjas II', 'Monjas II'), ('Vía club Sucre', 'Vía club Sucre'), ('Entrada Km5 vía la amistad', 'Entrada Km5 vía la amistad')], max_length=50, verbose_name='Calle / Sector'),
        ),
        migrations.AlterField(
            model_name='jefecalle',
            name='calle_nombre',
            field=models.CharField(choices=[('Monjas I', 'Monjas I'), ('Monjas II', 'Monjas II'), ('Vía club Sucre', 'Vía club Sucre'), ('Entrada Km5 vía la amistad', 'Entrada Km5 vía la amistad')], max_length=50, unique=True, verbose_name='Calle a Cargo'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='comite',
            field=models.CharField(choices=[('EJECUTIVO', 'Unidad Ejecutiva'), ('FINANZAS', 'Unidad Administrativa y Financiera'), ('CONTRALORIA', 'Unidad de Contraloría Social'), ('VIVIENDA', 'Vivienda y Hábitat '), ('SERVICIOS', 'Servicios Públicos (Agua, Luz, Gas)'), ('SALU', 'Salud Integral'), ('PROT', 'Protección Social y Familia'), ('ECON', 'Economía Comunal y Emprendimiento'), ('EDUC', 'Educación, Cultura y Formación'), ('DEPO', 'Deporte y Recreación'), ('JUV', 'Juventud y Nuevas Generaciones'), ('AMBI', 'Ambiente, Ecología y Aseo'), ('COMU', 'Medios y Comunicación Alternativa')], max_length=50, verbose_name='Comité / Categoría'),
        ),
        migrations.AlterField(
            model_name='voceria',
            name='comite_codigo',
            field=models.CharField(choices=[('EJECUTIVO', 'Unidad Ejecutiva'), ('FINANZAS', 'Unidad Administrativa y Financiera'), ('CONTRALORIA', 'Unidad de Contraloría Social'), ('VIVIENDA', 'Vivienda y Hábitat '), ('SERVICIOS', 'Servicios Públicos (Agua, Luz, Gas)'), ('SALU', 'Salud Integral'), ('PROT', 'Protección Social y Familia'), ('ECON', 'Economía Comunal y Emprendimiento'), ('EDUC', 'Educación, Cultura y Formación'), ('DEPO', 'Deporte y Recreación'), ('JUV', 'Juventud y Nuevas Generaciones'), ('AMBI', 'Ambiente, Ecología y Aseo'), ('COMU', 'Medios y Comunicación Alternativa')], max_length=20, verbose_name='Comité / Unidad'),
        ),
    ]
