# Generated by Django 6.0.5 on 2026-06-11 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0015_alter_habitante_calle_sector_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContadorConstancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('residencia', 'Constancia de Residencia'), ('comercial', 'Carta Aval Comercial')], max_length=20, unique=True)),
                ('ultimo_numero', models.IntegerField(default=0)),
            ],
        ),
    ]
