# Generated by Django 6.0.5 on 2026-06-13 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0016_contadorconstancia'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitante',
            name='causa_fallecimiento',
            field=models.TextField(blank=True, null=True, verbose_name='Causa de Fallecimiento'),
        ),
        migrations.AddField(
            model_name='habitante',
            name='fecha_fallecimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Fallecimiento'),
        ),
        migrations.AddField(
            model_name='habitante',
            name='hora_fallecimiento',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Hora de Fallecimiento'),
        ),
        migrations.AddField(
            model_name='habitante',
            name='vivo',
            field=models.BooleanField(default=True, verbose_name='¿Está vivo?'),
        ),
    ]
