# Generated by Django 6.0.5 on 2026-06-18 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0017_habitante_causa_fallecimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='comite',
            field=models.CharField(choices=[('FINANZAS', 'Unidad Administrativa y Financiera'), ('CONTRALORIA', 'Unidad de Contraloría Social'), ('VIVIENDA', 'Vivienda y Hábitat'), ('SERVICIOS', 'Servicios Públicos (Agua, Luz, Gas)'), ('SALU', 'Salud Integral'), ('ALIM', 'Alimentación y Defensa al Consumidor'), ('ECON', 'Economía Comunal'), ('EDUC', 'Educación, Cultura y Formación'), ('DEPO', 'Deporte y Recreación'), ('ECOS', 'Ecosocialismo'), ('PLAN', 'Planificación Comunal'), ('SEG', 'Seguridad y Defensa Integral')], max_length=50, verbose_name='Comité / Categoría'),
        ),
        migrations.AlterField(
            model_name='voceria',
            name='comite_codigo',
            field=models.CharField(choices=[('FINANZAS', 'Unidad Administrativa y Financiera'), ('CONTRALORIA', 'Unidad de Contraloría Social'), ('VIVIENDA', 'Vivienda y Hábitat'), ('SERVICIOS', 'Servicios Públicos (Agua, Luz, Gas)'), ('SALU', 'Salud Integral'), ('ALIM', 'Alimentación y Defensa al Consumidor'), ('ECON', 'Economía Comunal'), ('EDUC', 'Educación, Cultura y Formación'), ('DEPO', 'Deporte y Recreación'), ('ECOS', 'Ecosocialismo'), ('PLAN', 'Planificación Comunal'), ('SEG', 'Seguridad y Defensa Integral')], max_length=20, verbose_name='Comité / Unidad'),
        ),
    ]
